version: '3'

services:
  router:
    build:
      context: ./
      dockerfile: ./router/Dockerfile
    container_name: sailfish-router
    volumes:
      - ./router:/go/src/github.com/tallduck/sailfish-backend/router
      - ./vendor:/go/src/github.com/tallduck/sailfish-backend/vendor
      - ./helpers:/go/src/github.com/tallduck/sailfish-backend/helpers
      - ./protobuf:/go/src/github.com/tallduck/sailfish-backend/protobuf
    ports:
      - "3000:3000"
  auth:
    build:
      context: ./
      dockerfile: ./auth/Dockerfile
    container_name: sailfish-auth
    volumes:
      - ./auth:/go/src/github.com/tallduck/sailfish-backend/auth
      - ./vendor:/go/src/github.com/tallduck/sailfish-backend/vendor
      - ./helpers:/go/src/github.com/tallduck/sailfish-backend/helpers
      - ./protobuf:/go/src/github.com/tallduck/sailfish-backend/protobuf